"""
Memory Module — Episodic and Procedural Memory
Both use ChromaDB for persistent cross-session storage and semantic similarity retrieval.

Episodic memory:
    Stores complete past conversation episodes — successful and failed.
    Retrieved by the Coordinator before generating a plan.
    Used to avoid repeating past mistakes on similar questions.

Procedural memory:
    Stores verified successful question-SQL pairs only.
    Retrieved by the Coordinator and passed to the Coder as input hints.
    Used by the Coder as a starting reference when writing SQL.
"""

import hashlib
import sqlite3
import re as _re
import json as _json
from datetime import datetime

try:
    import chromadb
    from chromadb.utils import embedding_functions
    CHROMADB_AVAILABLE = True
except ImportError:
    CHROMADB_AVAILABLE = False
    print("[MEMORY] ChromaDB not installed — episodic and procedural memory disabled.")

CHROMA_PATH              = "./agent_memory_db"
EPISODIC_COLLECTION      = "episodic_memory"
PROCEDURAL_COLLECTION    = "procedural_memory"
EPISODIC_SIMILARITY_THRESHOLD  = 0.85
PROCEDURAL_SIMILARITY_THRESHOLD = 0.75


def _get_client():
    return chromadb.PersistentClient(path=CHROMA_PATH)


def _get_collection(name: str):
    client = _get_client()
    ef = embedding_functions.DefaultEmbeddingFunction()
    return client.get_or_create_collection(
        name=name,
        embedding_function=ef,
        metadata={"hnsw:space": "cosine"}
    )


def schema_hash(schema: str) -> str:
    """8-character MD5 hash of the schema — used to invalidate stale entries."""
    return hashlib.md5(schema.encode()).hexdigest()[:8]


# ─── Episodic Memory ──────────────────────────────────────────────────────────

def episodic_store(
    question: str,
    role: str,
    plan: dict,
    final_sql: str,
    verdict: str,
    retries_used: int,
    short_term: str,
    db_path: str,
    schema: str,
    user_id=None
) -> bool:
    """
    Stores a complete conversation episode in ChromaDB at session end.
    Called by the Coordinator after every completed conversation — pass or fail.

    The short_term string already contains the full narrative including
    retry reasons extracted naturally as the session progressed.

    Args:
        question:     original natural language question
        role:         "user" or "admin"
        plan:         the Plan tuple dict generated by the Coordinator
        final_sql:    the SQL that was ultimately executed (or last attempted)
        verdict:      "pass" or "fail"
        retries_used: how many coordinator retries occurred
        short_term:   the full short-term memory transcript of this session
        db_path:      path to the database
        schema:       the allowed_schema string used in this session

    Returns:
        True if stored successfully, False otherwise.
    """
    if not CHROMADB_AVAILABLE:
        return False
    try:
        collection = _get_collection(EPISODIC_COLLECTION)
        sh = schema_hash(schema)

        doc_id = hashlib.md5(
            f"{question.strip().lower()}{db_path}{sh}{datetime.utcnow().isoformat()}".encode()
        ).hexdigest()

        metadata = {
            "role":             role,
            "verdict":          verdict,
            "retries_used":     retries_used,
            "final_sql":        final_sql[:500],
            "db_path":          db_path,
            "schema_hash":      sh,
            "user_id":          str(user_id) if user_id is not None else "none",
            "timestamp":        datetime.utcnow().isoformat(),
            "goal":             plan.get("goal", ""),
            "operation":        plan.get("description", {}).get("operation", ""),
            "short_term":       short_term[:1000],
            "plan_description": _json.dumps(plan.get("description", {}))
        }

        collection.upsert(
            ids=[doc_id],
            documents=[question],
            metadatas=[metadata]
        )
        print(f"[EPISODIC MEMORY] Stored episode (verdict={verdict}, retries={retries_used}): {question[:60]}")
        return True
    except Exception as e:
        print(f"[EPISODIC MEMORY] Store error: {e}")
        return False

def clear_episodic_memory():
    if not CHROMADB_AVAILABLE:
        return
    try:
        client = _get_client()
        client.delete_collection(EPISODIC_COLLECTION)
        _get_collection(EPISODIC_COLLECTION)
        print("[EPISODIC MEMORY] Cleared and recreated successfully.")
    except Exception as e:
        print(f"[EPISODIC MEMORY] Error clearing: {e}")
        
def episodic_retrieve(
    question: str,
    db_path: str,
    schema: str,
    top_k: int = 2,
    user_id=None
) -> list:
    """
    Retrieves the top-k most similar past episodes from ChromaDB.
    Filters by schema_hash and db_path to avoid stale entries.
    Only returns entries with cosine similarity >= SIMILARITY_THRESHOLD.

    Returns list of dicts with keys:
        question, verdict, retries_used, final_sql, goal,
        operation, short_term, similarity
    """
    if not CHROMADB_AVAILABLE:
        return []
    try:
        collection = _get_collection(EPISODIC_COLLECTION)
        if collection.count() == 0:
            return []

        sh = schema_hash(schema)
        # For user role — filter by user_id so users only see their own episodes
        # For admin role — no user_id filter (user_id=None means no restriction)
        if user_id is not None:
            where = {
                "$and": [
                    {"schema_hash": {"$eq": sh}},
                    {"db_path":     {"$eq": db_path}},
                    {"user_id":     {"$eq": str(user_id)}}
                ]
            }
        else:
            where = {
                "$and": [
                    {"schema_hash": {"$eq": sh}},
                    {"db_path":     {"$eq": db_path}}
                ]
            }

        results = collection.query(
            query_texts=[question],
            n_results=min(top_k, collection.count()),
            where=where
        )

        episodes = []
        if results and results.get("documents") and results["documents"][0]:
            for i, doc in enumerate(results["documents"][0]):
                distance   = results["distances"][0][i]
                similarity = round(1 - (distance / 2), 3)
                if similarity >= EPISODIC_SIMILARITY_THRESHOLD:
                    meta = results["metadatas"][0][i]
                    episodes.append({
                        "question":         doc,
                        "verdict":          meta.get("verdict", ""),
                        "retries_used":     meta.get("retries_used", 0),
                        "final_sql":        meta.get("final_sql", ""),
                        "goal":             meta.get("goal", ""),
                        "operation":        meta.get("operation", ""),
                        "short_term":       meta.get("short_term", ""),
                        "similarity":       similarity,
                        "plan_description": _json.loads(meta.get("plan_description", "{}"))
                    })

        if episodes:
            print(f"[EPISODIC MEMORY] Retrieved {len(episodes)} episode(s) for: {question[:60]}")
        else:
            print("[EPISODIC MEMORY] No matching episodes found.")

        return episodes
    except Exception as e:
        print(f"[EPISODIC MEMORY] Retrieve error: {e}")
        return []


# ─── Procedural Memory ────────────────────────────────────────────────────────

def procedural_store(
    question: str,
    sql: str,
    db_path: str,
    schema: str,
    role: str = "admin",
    user_id=None
) -> bool:
    """
    Stores a verified successful question-SQL pair in ChromaDB.
    Called by the Coordinator only after verdict is pass AND execution succeeds.

    Args:
        question: original natural language question
        sql:      the verified SQL that produced the correct result
        db_path:  path to the database
        schema:   the allowed_schema string used in this session

    Returns:
        True if stored successfully, False otherwise.
    """
    if not CHROMADB_AVAILABLE:
        return False
    try:
        collection = _get_collection(PROCEDURAL_COLLECTION)

        # Deduplication — skip if a near-identical entry already exists
        dedup_results = collection.query(
            query_texts=[question],
            n_results=1,
            where={"db_path": db_path}
        )
        if dedup_results and dedup_results["distances"] and dedup_results["distances"][0]:
            distance = dedup_results["distances"][0][0]
            similarity = 1 - distance
            if similarity >= 0.99:
                print(f"[MEMORY] Procedural dedup — near-identical entry exists "
                      f"(similarity={similarity:.2f}), skipping store")
                return False

        sh = schema_hash(schema)

        # Deterministic ID — same question on same schema overwrites old entry
        doc_id = hashlib.md5(
            f"{question.strip().lower()}{db_path}{sh}".encode()
        ).hexdigest()

        collection.upsert(
            ids=[doc_id],
            documents=[question],
            metadatas=[{
                "sql":         sql,
                "db_path":     db_path,
                "schema_hash": sh,
                "role":        role,
                "user_id":     str(user_id) if user_id is not None else "none",
                "timestamp":   datetime.utcnow().isoformat()
            }]
        )
        print(f"[PROCEDURAL MEMORY] Stored: {question[:60]}")
        return True
    except Exception as e:
        print(f"[PROCEDURAL MEMORY] Store error: {e}")
        return False


def procedural_retrieve(
    question: str,
    db_path: str,
    schema: str,
    top_k: int = 3,
    role: str = "admin",
    user_id=None
) -> list:
    """
    Retrieves top-k verified SQL hints for similar past questions.
    Filters by schema_hash and db_path.
    Only returns entries with cosine similarity >= SIMILARITY_THRESHOLD.

    Returns list of dicts with keys: question, sql, similarity
    """
    if not CHROMADB_AVAILABLE:
        return []
    try:
        collection = _get_collection(PROCEDURAL_COLLECTION)
        if collection.count() == 0:
            return []

        sh = schema_hash(schema)
        if role == "user" and user_id is not None:
            where = {
                "$and": [
                    {"db_path":     {"$eq": db_path}},
                    {"schema_hash": {"$eq": sh}},
                    {"role":        {"$eq": "user"}},
                    {"user_id":     {"$eq": str(user_id)}}
                ]
            }
        else:
            where = {
                "$and": [
                    {"db_path":     {"$eq": db_path}},
                    {"schema_hash": {"$eq": sh}},
                    {"role":        {"$eq": "admin"}}
                ]
            }

        results = collection.query(
            query_texts=[question],
            n_results=min(top_k, collection.count()),
            where=where
        )

        hints = []
        if results and results.get("documents") and results["documents"][0]:
            for i, doc in enumerate(results["documents"][0]):
                distance   = results["distances"][0][i]
                similarity = round(1 - (distance / 2), 3)
                if similarity >= PROCEDURAL_SIMILARITY_THRESHOLD:
                    meta = results["metadatas"][0][i]
                    hints.append({
                        "question":   doc,
                        "sql":        meta.get("sql", ""),
                        "similarity": similarity
                    })

        if hints:
            print(f"[PROCEDURAL MEMORY] Retrieved {len(hints)} hint(s) for: {question[:60]}")
        else:
            print("[PROCEDURAL MEMORY] No matching hints found.")

        return hints
    except Exception as e:
        print(f"[PROCEDURAL MEMORY] Retrieve error: {e}")
        return []


# ─── Utilities ────────────────────────────────────────────────────────────────

def episodic_count() -> int:
    if not CHROMADB_AVAILABLE:
        return 0
    try:
        return _get_collection(EPISODIC_COLLECTION).count()
    except Exception:
        return 0


def procedural_count() -> int:
    if not CHROMADB_AVAILABLE:
        return 0
    try:
        return _get_collection(PROCEDURAL_COLLECTION).count()
    except Exception:
        return 0


def clear_procedural_memory():
    """
    Deletes and recreates the procedural memory collection.
    Called before benchmark runs to start with a clean slate.
    """
    if not CHROMADB_AVAILABLE:
        print("[PROCEDURAL MEMORY] ChromaDB not available — cannot clear.")
        return
    try:
        client = _get_client()
        client.delete_collection(PROCEDURAL_COLLECTION)
        _get_collection(PROCEDURAL_COLLECTION)
        print("[PROCEDURAL MEMORY] Cleared and recreated successfully.")
    except Exception as e:
        print(f"[PROCEDURAL MEMORY] Error clearing: {e}")


# ─── Semantic Memory — Persistent Schema Store ────────────────────────────────

SEMANTIC_DB_PATH = "./semantic_memory.db"


def _get_semantic_conn():
    """Returns a connection to the semantic memory database and ensures schema_store table exists."""
    conn = sqlite3.connect(SEMANTIC_DB_PATH)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS schema_store (
            db_path        TEXT PRIMARY KEY,
            schema_version INTEGER NOT NULL,
            full_schema    TEXT NOT NULL,
            stored_at      TEXT NOT NULL
        )
    """)
    conn.commit()
    return conn


def get_full_schema_cached(db_path: str, get_schema_fn) -> str:
    """
    Returns the full database schema from persistent store if valid.
    Uses PRAGMA schema_version to detect schema changes — SQLite increments
    this integer on every CREATE TABLE, DROP TABLE, or ALTER TABLE.
    Falls back to reading from the database and stores the result.

    Args:
        db_path:       path to the SQLite database
        get_schema_fn: function to read full schema from database (get_schema from database.py)

    Returns:
        Full schema string containing all CREATE TABLE statements.
    """
    try:
        # Read current schema version from source database
        src = sqlite3.connect(db_path)
        current_version = src.execute("PRAGMA schema_version;").fetchone()[0]
        src.close()

        conn = _get_semantic_conn()
        row = conn.execute(
            "SELECT schema_version, full_schema FROM schema_store WHERE db_path = ?",
            (db_path,)
        ).fetchone()

        if row and row[0] == current_version:
            print(f"[SEMANTIC MEMORY] Schema cache hit for {db_path} (version {current_version})")
            conn.close()
            return row[1]

        # Cache miss or schema changed — read from source database
        print(f"[SEMANTIC MEMORY] Schema cache miss for {db_path} — reading from database...")
        full_schema = get_schema_fn(db_path)

        conn.execute(
            "INSERT OR REPLACE INTO schema_store VALUES (?, ?, ?, ?)",
            (db_path, current_version, full_schema, datetime.utcnow().isoformat())
        )
        conn.commit()
        conn.close()
        print(f"[SEMANTIC MEMORY] Schema stored for {db_path} (version {current_version})")
        return full_schema

    except Exception as e:
        print(f"[SEMANTIC MEMORY] Schema cache error: {e} — falling back to direct read")
        return get_schema_fn(db_path)


def build_filtered_schema_from_string(full_schema: str, role: str, role_permissions: dict) -> str:
    """
    Filters the full schema string to only permitted tables and columns for the given role.
    No database access needed — parses the CREATE TABLE statements from the schema string directly.
    This replaces build_filtered_schema which required PRAGMA database queries.

    Args:
        full_schema:      complete schema string with all CREATE TABLE statements
        role:             the user role to filter for
        role_permissions: the ROLE_PERMISSIONS dict from query_agent.py

    Returns:
        Filtered schema string containing only permitted tables and columns.
    """
    perms = role_permissions.get(role, {})
    allowed_tables = perms.get("allowed_tables", [])
    allowed_columns = perms.get("allowed_columns", {})

    # Split schema into individual CREATE TABLE blocks
    blocks = _re.split(r'(?=CREATE TABLE)', full_schema.strip(), flags=_re.IGNORECASE)
    schema_parts = []

    for block in blocks:
        block = block.strip()
        if not block:
            continue

        # Extract table name
        match = _re.match(r'CREATE TABLE\s+["\']?(\w+)["\']?', block, _re.IGNORECASE)
        if not match:
            continue
        table_name = match.group(1)

        if table_name not in allowed_tables:
            continue

        permitted = allowed_columns.get(table_name)
        if permitted is None:
            # All columns permitted — keep block as is
            schema_parts.append(block)
            continue

        # Filter to permitted columns only
        lines = block.split('\n')
        filtered_lines = []
        inside_table = False

        for line in lines:
            stripped = line.strip()

            # Always keep the CREATE TABLE header line
            if _re.match(r'CREATE TABLE', stripped, _re.IGNORECASE):
                filtered_lines.append(line)
                inside_table = True
                continue

            # Always keep the closing paren
            if stripped.startswith(')'):
                filtered_lines.append(line)
                continue

            if inside_table:
                # Check if this line defines a permitted column
                col_match = _re.match(r'\s*["\']?(\w+)["\']?\s+\w+', line)
                if col_match:
                    col_name = col_match.group(1)
                    if col_name in permitted:
                        filtered_lines.append(line)
                else:
                    # Table constraint line — keep it
                    filtered_lines.append(line)

        if filtered_lines:
            schema_parts.append('\n'.join(filtered_lines))

    return '\n\n'.join(schema_parts)


def schema_store_count() -> int:
    """Returns the number of databases with cached schemas."""
    try:
        conn = _get_semantic_conn()
        count = conn.execute("SELECT COUNT(*) FROM schema_store").fetchone()[0]
        conn.close()
        return count
    except Exception:
        return 0
